# dbt/profiles.yml
netflix:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "hec19639.us-east-1"
      user: "SHIVANG26"
      password: "Shivang@123444"
      role: "ACCOUNTADMIN"
      # Yahan par humne sahi database ka naam dala hai jo aapne banaya tha
      database: "netflix_db"
      warehouse: "COMPUTE_WH"
      schema: "PUBLIC"
      threads: 1
      client_session_keep_alive: false